### ISSUE TITLE
all authentication requests, except login & registration, are failing

### ISSUE THREAD

**Issue by bbarbersox** [gaand/project2-api#5]
Can register and login successfully and can actually requests data from server & get it back but any request that requires authentication is failing.

**Comment by gaand** [comment]
Hi Bill,

Would you please provide a little more context:  How are you invoking your API (curl, postman, your own javascript); Are you getting any error messages from rails or otherwise?

Please reply with that information.  Thanks.

**Comment by bbarbersox** [comment]
my own javascript.  seems to work with curl when copying in the token.  Let me review the other issue you identified in the repo.  also just made a change that may have resolved it.  still need to test.

**Comment by gaand** [comment]
Saad helped Bill with this off an issue Bill created on https://github.com/ga-wdi-boston/rails-project-full-stack-app/issues
