### ISSUE TITLE
Parameters error when creating property from browser/javascript.  Works with curl.  Details below. Cannot resolve.

### ISSUE THREAD

**Issue by bbarbersox** [gaand/project2-api#6]
Error when PropertiesController invoked from Browser

Started POST "/properties" for ::1 at 2015-11-11 09:55:22 -0500
Processing by PropertiesController#create as HTML
  Parameters: {"{\"property\":{\"no\":\"12\",\"street\":\"Fuller Street\",\"city\":\"Sheldon\",\"state\":\"NH\",\"zip\":\"34876\",\"house_mgmt_co\":\"Holsten Holdings\",\"manager\":\"Matt Savrest\",\"user_id\":3}}"=>nil}
  User Load (1.5ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "4cc8af9ed51fe85dd117c0d615a2621a"]]
Completed 400 Bad Request in 5ms (ActiveRecord: 1.5ms)

ActionController::ParameterMissing (param is missing or the value is empty: property):
  app/controllers/properties_controller.rb:48:in `property_params'
  app/controllers/properties_controller.rb:18:in`create'

  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.5ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (43.6ms)

Successful completion when add property invoked via curl
Started POST "/properties" for ::1 at 2015-11-11 10:07:22 -0500
Processing by PropertiesController#create as _/_
  Parameters: {"property"=>{"no"=>"56", "street"=>"Weston Drive", "city"=>"Ashton", "state"=>"KY"}}
  User Load (0.2ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "4cc8af9ed51fe85dd117c0d615a2621a"]](0.2ms)  BEGIN
  SQL (1.0ms)  INSERT INTO "properties" ("no", "street", "city", "state", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["no", "56"], ["street", "Weston Drive"], ["city", "Ashton"], ["state", "KY"], ["user_id", 3], ["created_at", "2015-11-11 15:07:22.955276"], ["updated_at", "2015-11-11 15:07:22.955276"]](0.3ms)  COMMIT
Completed 201 Created in 17ms (Views: 1.8ms | ActiveRecord: 2.4ms)

**Comment by gaand** [comment]
I believe this issue has been addressed on the rails-project-full-stack-app repo's issues.
